language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  edge: true
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: GNhh0iLz1Y85qH0W0ufibNMJJHHCSfdA50EnA77WQi4CGMSTmEh9yfqQRDhqr3YnkHEcHdkInrHEjWj6pp/my9hNCxv7bfzy+W+nkRvYTp9N6ebFdOXmB7kwQ1+BfiOYcEUVnf2FQNB+3FVk26q/2TsmIKRIf/OCd4WwoE47mKG6b/r115DGfqx0SqFfa19zt5KQwXCP39MLa+AclsTdkBWspU1Cg0yF03/LP+Zi21fb0AgJKcMjTC9m7LKe1Nh2axEMsRs+HIRYlot1QqEhoTRwkAla6zMDwfKGsmV7CwkLtFri+f+YNyqeLUfU+yVZ5Y6XgwwW6KgTalH6MxGCD575gphePXFlJhzT34ek/O3n3BuIlq1Ij/FBqWaNwQdDPlTPdJBljiXQIKvepddW8JP1Usxer+lhiZAUZ6GIIW+C4RUk5JNCCOsTb8PJrD4kHL6raS7n6pLgVWPvGSS7JFg1Zm2pv4GXDedbmob22KQsRQaXve294pLU3Wvsg9N+VHpsIQYZ51DhtZZOJ6jdANWQYBkSkGd9oJmUMAXOcgTmKMRza4vE0RPTh8mbiM7jAE15Pk0r/NIgYDhgT69NJB1azbVL7YAowbq140j2wn+vi3YCPetj2LYJU1sYRymk6k1Df6Pa7QOJATmBk+LVZy7HIK0+jr0qTgTsH0Dh/ac=
  on:
    tags: true
    repo: serge-m/simplebbox
    python: 3.8
