language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  edge: true
  distributions: sdist bdist_wheel
  username: serge-m
  password:
    secure: TCO+g3Ch2f3DQiQYtSGnfukwSfCaVhjL1h92WCOOr5RHKNfd6p99QiSFSJrar4ss6RS3q+FEH/A6yKPRdyjs/a7uYaqdMGhZd19Fv2aAtjBhsxDnIOjg5kge9K57hqdwjpEg8PQom4PS06GaMaEbGI6go54cvIFuiLX7CCU7zeypLQdaC/xDvsh8wppjtuAHe2M7/m1IcjDkcJLuCVs+mZOMY3NKdspRCVuK9iCofJu5bYPN/LCOMyRdZbwgu85QPwU0eKJS8vOr0STjrg7OeAPmi7GfurVnmztKetyaZprv5e5NP8X5arNStFz1Rz+6lc9WM6Dr4xU2Ov91uWQqilBLHxHFAiR/ObwqOoRDma0sVdp1C/syE0EmGO2AWbWvr1uW5m4sNNkLZc4reR+d1OlUVyhus6nkGqZRFtTET3UdM9CpuUuVxUOPCJdXIAqKVqGabzQf116dNz/Xyg4f6FunI3jLGJuUHB06nkrIkn1Or08SBeT4sNaXcKM7VhfeeWD9Q+1LFBDE/80m9JyEe/fSLpeuTc6c5ZhPM2t9el1b0T7ivZfvVeqXxEKk8Xyt1arBimokoc9tZ9n9koNDjntui1+bSibbPHT8DO5TVKLgcSZ2wBjwGKh0/fWq/7cHiAvchTdLZ5WO+zspAWA/+IQRH5szM7BGnzq0tK+ij6g=
  on:
    tags: true
    repo: serge-m/simplebbox
    python: 3.6
